language: php
php:
- 5.5.9
- 5.6
- 7.0
before_script:
- cp .env.example .env
- sqlite3 storage/1516showtime.db ""
- composer self-update
- composer install --no-interaction --prefer-source --dev
- php artisan migrate
- php artisan db:seed
- php artisan key:generate
script: vendor/bin/phpunit
deploy:
  provider: heroku
  api_key:
    secure: Nq2a89JnsIxNCjU0UrLhsLUiwHgcbWsVyHHZHaPnBxekVOb3YpXVTE/JVRA2UDUrjFmFIGBlYnVfXWouFBbwlLP/WWxg8N3AH8KJPgi5nMHFQkbuvhTaTJOxLS7YpSgybPv8mc5Hc/eHYxt4gdhSVSHmNGFPdGWZsd5MtwMeuhwwgCQcNffsqXrTGw93Fsbdbc7m0ZLkHFaUNEhuqpUpZvgxpEe/qaGNLlzfZW4E2I8xcLugXerZgxyrKm+WaVi2sHW4T0LOirRVe1mzsCtT9GWUvpykZgV+bUYBNy+wlADqSVq/uPzmEU3Ga1uPTf45P0mfVW0acxuYsKTdoCUY2nM7nCHK3AYnbDfByVUMJAuYdUVjYlSn2dc9mYD90u1wxxcWA0i/KlZzCSGNa0THOikirkRJuOQNcKY0u0LLsPjwuWAt3Sq8junWIX5eUbAiEuC9BgnnjQil4F/T7TgTEJbiAPdxTU4QU2gPaXP3m7k9PDwMa3m63bhba3LShEMlq6WjeBNBWjj26IkXYeKH5wVkVUt78OSGfjew48qFz0Od9mtzEZ4FHT2MQ+rwcgZLzJNq/yfTBr6SD53k+BFMzBcvTeMsVNU0ldHYrLLyR8aIX8E+LailSINnLR/WcwHfF6rf3lNTh7rabbzVKEFMlEMDGaXcyi0dGSceLZnos6o=
  app: floating-shelf-62197